@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

'LAYOUT_WITH_LEGEND()

title Component diagram for LIVORA


Container(spa, "Single-Page App", "Typescript, ReactJS", "Provides the UI to showcase the user age")
Container(backend_api, "API Age", "Typescript, Nodejs Lambda", "Provides Age expectancy functionality via API")


Container_Boundary(spa, "Single-Page App") {
    Component(user_data_control, "User Data Controller", "Flow Manager", "Manage the current user data, input and viewing of life/death")
    Component(data_manager, "Age Data Manager", "Context Component", "Load the user info from the URL or from the localStorage/cookies")
    Component(input_form, "User Input Form", "Component Form", "Let the user enter its data skipping also data it doesnt want to enter like sex or country.")
    Component(age_viewer, "Age Viewer", "Component", "Showcase the user age with different possible layouts that can be changed")

    Rel(user_data_control, data_manager, "Uses")
    Rel(user_data_control, input_form, "Uses")
    Rel(user_data_control, age_viewer, "Uses")
}

Rel(data_manager, backend_api, "Uses", "JSON/HTTPS")


@enduml