@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title System Context diagram for LIVORA

Person(user, "User of the web PWA", "Anyone having a URL or local data to see progress age")
System(livora_system, "LIVORA Netlify App", "Allows users to see their current life progress")

Rel(user, livora_system, "Uses")

@enduml